---
- name: Create garage group
  ansible.builtin.group:
    name: "{{ garage_group }}"
    system: true
    state: present

- name: Create garage user
  ansible.builtin.user:
    name: "{{ garage_user }}"
    group: "{{ garage_group }}"
    system: true
    create_home: true
    home: "{{ garage_home }}"
    shell: /sbin/nologin
    state: present

- name: Create configuration directory
  ansible.builtin.file:
    path: "{{ garage_config_dir }}"
    state: directory
    owner: root
    group: "{{ garage_group }}"
    mode: "0750"

- name: Create data directories
  ansible.builtin.file:
    path: "{{ item.path if item is mapping else item }}"
    state: directory
    owner: "{{ garage_user }}"
    group: "{{ garage_group }}"
    mode: "0755"
  loop: >-
    {{
      (garage_data_dirs | default([]) | length > 0)
      | ternary(garage_data_dirs, [garage_data_dir])
      + [garage_metadata_dir]
    }}
